### ISSUE TITLE
Cross-compile modules for Scala 3

### ISSUE THREAD

**Issue by DieBauer** [hseeberger/akka-http-json#755]
- [x] akka-http-argonaut (see #754 )
- [X] ~~akka-http-avro4s~~ avro4s-json module does not have a Scala 3 flavour and is [removed from project](https://github.com/sksamuel/avro4s/commit/7066b4dbeb822aa77025e805a11d759c70546ad4)
- [ ] akka-http-circe 
- [ ] akka-http-jackson
- [x] akka-http-json4s (see #754 )
- [x] akka-http-jsoniter-scala (see #754 )
- [ ] akka-http-ninny
- [ ] akka-http-play-json - In progress https://github.com/playframework/playframework/issues/11260
- [ ] akka-http-upickle 
- [x] akka-http-zio-json (see #754 )

And of course akka (or Pekko) itself, currently the akka-http modules are not cross-published for Scala 3

**Comment by luksow** [comment]
@DieBauer since akka-http has a 10.5.0-M1 release for Scala 3 (e.g. https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-core_3/10.5.0-M1/) what are the next steps planned here?

**Comment by pjfanning** [comment]
If you want to support Jackson for Scala 3, you can look at a change I made to my Pekko fork of this lib. I removed the scala-reflect dependency that akka-http-jackson has and started using jackson-module-scala's ClassTagExtensions to support getting class information from implicit ClassTags. 

* https://github.com/hseeberger/akka-http-json/commit/4e909d93389f26a7bea852df1df1d64db12d9676
* https://github.com/hseeberger/akka-http-json/commit/973c3e235642dd111d2a331752a4c97b61176bd8 (small mods to get code to compile in Scala 3)

**Comment by DieBauer** [comment]
@pjfanning  I think we did the same changes, see #757 for the jackson scala 3 support :) 

@luksow, I can update akka version as well. But I'm not sure when a release will be cut with the other modules in as well, @hseeberger what is your idea of this project?

**Comment by hseeberger** [comment]
I'd love to find other maintainers, because currently I have no time to work on it.

**Comment by pjfanning** [comment]
If we can get a few volunteers together to maintain these libs and their pekko equivalents, I guess I can help out.
